### ISSUE TITLE
transfer learning code

### ISSUE THREAD

**Issue by xuy2** [openai/finetune-transformer-lm#18]
Have you released the code for language model training?

**Comment by xuy2** [comment]
I'd like to use the code you provided to finish seq2seq task such as POS and Named Entity Recognition. However, the preprocessing way in your code is to divide the words which are not frequent. I don't know how to use the divided word to finish Named Entity Recognition... Therefore, I'd like to retrain the transfer language model by myself. Can I kindly know the training time?

**Comment by wugh** [comment]
I'm trying to training the language model on Chinese. Maybe we can discussion some experience.

**Comment by madisonmay** [comment]
@xuy2 we're talking using this code for sequence labeling tasks over at [our fork of the repo](https://github.com/IndicoDataSolutions/finetune).  Docs for the `SequenceLabeler` wrapper class are [here](https://finetune.indico.io/#finetune.SequenceLabeler.finetune).  We've thought a little bit about how to deal with the problem of predictions being made at the subtoken level and opted to simply round predictions off to the nearest token as a post processing step.  You can optionally disable this behavior in the config.

If you end up adapting the code in this repo you may want to consider adding one more attention block on top of the model to give the model some forward context, because as it currently stands future tokens are masked off from the model's representation of the sequence.

**Comment by xuy2** [comment]
@madisonmay Thanks for your excellent work.

**Comment by xuy2** [comment]
@wugh I sent you an e-mail to the address in your profile.
